package so.dun.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.9
 * 2016-02-09T19:03:12.442+08:00
 * Generated source version: 2.5.9
 * 
 */
@WebService(targetNamespace = "http://webservice.dun.so/", name = "StudentDao")
@XmlSeeAlso({ObjectFactory.class})
public interface StudentDao {

    @WebMethod
    @RequestWrapper(localName = "getAllStudentsMap", targetNamespace = "http://webservice.dun.so/", className = "so.dun.webservice.GetAllStudentsMap")
    @ResponseWrapper(localName = "getAllStudentsMapResponse", targetNamespace = "http://webservice.dun.so/", className = "so.dun.webservice.GetAllStudentsMapResponse")
    @WebResult(name = "_return", targetNamespace = "")
    public so.dun.webservice.GetAllStudentsMapResponse.Return getAllStudentsMap();

    @WebMethod
    @RequestWrapper(localName = "getStudentById", targetNamespace = "http://webservice.dun.so/", className = "so.dun.webservice.GetStudentById")
    @ResponseWrapper(localName = "getStudentByIdResponse", targetNamespace = "http://webservice.dun.so/", className = "so.dun.webservice.GetStudentByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public so.dun.webservice.Student getStudentById(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Integer arg0
    );

    @WebMethod
    @RequestWrapper(localName = "addStudent", targetNamespace = "http://webservice.dun.so/", className = "so.dun.webservice.AddStudent")
    @ResponseWrapper(localName = "addStudentResponse", targetNamespace = "http://webservice.dun.so/", className = "so.dun.webservice.AddStudentResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean addStudent(
        @WebParam(name = "arg0", targetNamespace = "")
        so.dun.webservice.Student arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getStudentsByPrice", targetNamespace = "http://webservice.dun.so/", className = "so.dun.webservice.GetStudentsByPrice")
    @ResponseWrapper(localName = "getStudentsByPriceResponse", targetNamespace = "http://webservice.dun.so/", className = "so.dun.webservice.GetStudentsByPriceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<so.dun.webservice.Student> getStudentsByPrice(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
