package so.dun.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.9
 * 2016-02-09T19:03:12.486+08:00
 * Generated source version: 2.5.9
 * 
 */
@WebServiceClient(name = "StudentDaoImplService", 
                  wsdlLocation = "http://localhost:8080/WSServer/StudentWS?wsdl",
                  targetNamespace = "http://webservice.dun.so/") 
public class StudentDaoImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.dun.so/", "StudentDaoImplService");
    public final static QName StudentDaoImplPort = new QName("http://webservice.dun.so/", "StudentDaoImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/WSServer/StudentWS?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(StudentDaoImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/WSServer/StudentWS?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public StudentDaoImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public StudentDaoImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentDaoImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public StudentDaoImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public StudentDaoImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public StudentDaoImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns StudentDao
     */
    @WebEndpoint(name = "StudentDaoImplPort")
    public StudentDao getStudentDaoImplPort() {
        return super.getPort(StudentDaoImplPort, StudentDao.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StudentDao
     */
    @WebEndpoint(name = "StudentDaoImplPort")
    public StudentDao getStudentDaoImplPort(WebServiceFeature... features) {
        return super.getPort(StudentDaoImplPort, StudentDao.class, features);
    }

}
